require('module-alias/register')
const chalk = require('chalk')
const config = require('config')
const express = require('express')
const bodyParser = require('body-parser')
const session = require('express-session')
const cookieParser = require('cookie-parser')
const userRouter = require('@/routes/user.route')
const articleRouter = require('@/routes/article.route')
const commentRouter = require('@/routes/comment.route')
const unitRouter = require('@/routes/unit.router')
const swaggerInstall = require('@/utils/swagger.unit')

const app = express()
swaggerInstall(app)
app.use(cookieParser())
app.use(bodyParser.json())
app.use(session(config.get('session')))
app.use('/gimishare/api/v1/users', userRouter)
app.use('/gimishare/api/v1/articles', articleRouter)
app.use('/gimishare/api/v1/comments', commentRouter)
app.use('/gimishare/api/v1/unit', unitRouter)

app.listen(config.get('server.port'), () => {
  console.log('app listening on server ' + chalk.green(`http://${config.get('server.host')}:${config.get('server.port')}`))
})
